export default  [
        {
            "Code": "AP",
            "Name": "ASHISH PATEL",
            "Address": "H-103 Melbourne Life Style, Opp; Amrutam",
            "Address_2": "Education Campus, New Shahibag Nana Chiloda",
            "City": "AHMEDABAD",
            "State": "GJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9173488678",
            "ETag": "20;DQAAAAJ7/0EAUAAAAAAA10;33000696290;"
        },
        {
            "Code": "AS",
            "Name": "ANIL SAMBHANI",
            "Address": "S/o. Parasram, E-7, Guru Teg Bhadur Colony,",
            "Address_2": "Sikandra,",
            "City": "AGRA",
            "State": "UP",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "8191018741",
            "ETag": "20;DQAAAAJ7/0EAUwAAAAAA10;33073275430;"
        },
        {
            "Code": "BD",
            "Name": "BHAUTIK DEVALIYA",
            "Address": "C/O VISHWA STORE PIPLI CHORA ",
            "Address_2": "",
            "City": "MANGROL",
            "State": "GJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "8141643189",
            "ETag": "20;DQAAAAJ7/0IARAAAAAAA10;33587580280;"
        },
        {
            "Code": "CP",
            "Name": "CHETAN PARMAR",
            "Address": "Opp Ishwar Krupa house Close Street",
            "Address_2": "Ambedkar Nagar Sheri No 6 Opp. A.G,Nana mauva Main",
            "City": "RAJKOT",
            "State": "GJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9909062794",
            "ETag": "20;DQAAAAJ7/0MAUAAAAAAA10;33073332320;"
        },
        {
            "Code": "DV",
            "Name": "DINESH VEGADA",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "8980318740",
            "ETag": "20;DQAAAAJ7/0QAVgAAAAAA10;32985045930;"
        },
        {
            "Code": "HK",
            "Name": "HITESH KUMAR",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "20;DQAAAAJ7/0gASwAAAAAA10;32985051030;"
        },
        {
            "Code": "HP",
            "Name": "HARSH PUJARA",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "20;DQAAAAJ7/0gAUAAAAAAA10;32953244030;"
        },
        {
            "Code": "JB",
            "Name": "JAYESH JOBANPUTRA",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9898900090",
            "ETag": "20;DQAAAAJ7/0oAQgAAAAAA10;32985051080;"
        },
        {
            "Code": "JV",
            "Name": "JITENDRA VYAS",
            "Address": "59, OLD RUSHIRAJNAGAR",
            "Address_2": " DESAI NAGAR, BEHIND CHITRA PETROL PUMP",
            "City": "BHAVNAGAR",
            "State": "GJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "8849355652",
            "ETag": "20;DQAAAAJ7/0oAVgAAAAAA10;33073338540;"
        },
        {
            "Code": "MC",
            "Name": "MAHESH CHAWLA",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9904160288",
            "ETag": "20;DQAAAAJ7/00AQwAAAAAA10;32953244060;"
        },
        {
            "Code": "NJ",
            "Name": "NARENDRA JOSHI",
            "Address": "Post - Motipura,",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "20;DQAAAAJ7/04ASgAAAAAA10;34607215780;"
        },
        {
            "Code": "NP",
            "Name": "NILESH PATEL",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9510096060",
            "ETag": "20;DQAAAAJ7/04AUAAAAAAA10;32953244080;"
        },
        {
            "Code": "PJ",
            "Name": "PANKAJ JANGID",
            "Address": "S/O, Amrutlal, 8, Bada Bas Dhola Chotara, Pali",
            "Address_2": "",
            "City": "PALI",
            "State": "RJ",
            "Post_Code": "306401",
            "Whatsapp_Mobile_Number": "8209035770",
            "ETag": "20;DQAAAAJ7/1AASgAAAAAA10;33703661050;"
        },
        {
            "Code": "RA",
            "Name": "RAJPAL ALANI",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "20;DQAAAAJ7/1IAQQAAAAAA10;32985065310;"
        },
        {
            "Code": "RD",
            "Name": "RAJESH DASWANI",
            "Address": "02,56 Quarters Tila Jamalpura",
            "Address_2": "Bhopal Tehsil Huzur",
            "City": "BHOPAL",
            "State": "MP",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "6260609480",
            "ETag": "20;DQAAAAJ7/1IARAAAAAAA10;33703696660;"
        },
        {
            "Code": "RIDDHI",
            "Name": "RIDDHI SHANKAR SHARMA",
            "Address": "HOUSE NO.448/7.IMALI MAHOLLA",
            "Address_2": "",
            "City": "AJMER",
            "State": "RJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "32;DQAAAAJ7/1IASQBEAEQASABJAAAAAAA=10;33610748910;"
        },
        {
            "Code": "RK",
            "Name": "RAKESH KUMAR",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "7719655145",
            "ETag": "20;DQAAAAJ7/1IASwAAAAAA10;32985071720;"
        },
        {
            "Code": "RP",
            "Name": "RAMESH PRAJAPAT",
            "Address": "64 meenaxi motors,",
            "Address_2": "College Road, Janta colony",
            "City": "PALI",
            "State": "RJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "8875600099",
            "ETag": "20;DQAAAAJ7/1IAUAAAAAAA10;33073389910;"
        },
        {
            "Code": "RS",
            "Name": "RAJENDER SHARMA",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "20;DQAAAAJ7/1IAUwAAAAAA10;32985077300;"
        },
        {
            "Code": "SD",
            "Name": "SITARAM DADHICH",
            "Address": "S% Balkishan ji, Bharmino ka tiba",
            "Address_2": "MakranaDist :- Nagour (raj.)",
            "City": "NAGOUR",
            "State": "RJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9413681563",
            "ETag": "20;DQAAAAJ7/1MARAAAAAAA10;33073438490;"
        },
        {
            "Code": "SELF",
            "Name": "SELF",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "",
            "ETag": "28;DQAAAAJ7/1MARQBMAEYAAAAAAA==10;32953244170;"
        },
        {
            "Code": "SS",
            "Name": "SUNIL SHRIVASTAV",
            "Address": "Rampur Baldiha,Matakoya,",
            "Address_2": "MAHARAJGANJ                        ",
            "City": "",
            "State": "UP",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9936170815",
            "ETag": "20;DQAAAAJ7/1MAUwAAAAAA10;33073486290;"
        },
        {
            "Code": "TP",
            "Name": "TUSHAR PANCHAL",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9428076880",
            "ETag": "20;DQAAAAJ7/1QAUAAAAAAA10;33703698240;"
        },
        {
            "Code": "UP",
            "Name": "UMESH PRAJAPATI",
            "Address": "C/203 Agambaug Appartment Bawri Kumbharwada ,",
            "Address_2": "Ranmukteshvar Road,Pratapnagar,",
            "City": "BARODA",
            "State": "GJ",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "9537796844",
            "ETag": "20;DQAAAAJ7/1UAUAAAAAAA10;33073394490;"
        },
        {
            "Code": "VS",
            "Name": "VIPIN SINGH",
            "Address": "",
            "Address_2": "",
            "City": "",
            "State": "",
            "Post_Code": "",
            "Whatsapp_Mobile_Number": "7709996615",
            "ETag": "20;DQAAAAJ7/1YAUwAAAAAA10;32985092410;"
        }
    ]